version: '3.9'

services:
  kong-database:
    image: postgres:9.6
    # ports:
    #   - '5432:5432'
    volumes:
      - /var/book-exchange/kong-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${KONG_PG_USER}
      - POSTGRES_DB=${KONG_PG_DB}
      - POSTGRES_PASSWORD=${KONG_PG_PASSWORD}
  # Kong API Gateway
  kong-migration:
    image: kong/kong-gateway:2.8.1.0-alpine
    command: 'kong migrations bootstrap'
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PG_DATABASE=${KONG_PG_DB}
    links:
      - kong-database
    depends_on:
      - kong-database
  kong-gateway:
    image: kong/kong-gateway:2.8.1.0-alpine
    ports:
      - '${KONG_GW_UPSTREAM_HTTP_PORT}:8000'
      - '${KONG_GW_ADMIN_HTTP_PORT}:8001'
      - '${KONG_GW_UPSTREAM_HTTPS_PORT}:8443'
      - '${KONG_GW_ADMIN_HTTPS_PORT}:8444'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PG_DATABASE=${KONG_PG_DB}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      # - KONG_PLUGINS=kong-auth-middleware
    links:
      - kong-database
    depends_on:
      - kong-database
      - kong-migration
  konga-prepare:
    image: pantsel/konga:next
    command: '-c prepare -a postgres -u postgresql://${KONG_PG_USER}:${KONG_PG_PASSWORD}@kong-database:5432/${KONG_PG_DB}'
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga:next
    ports:
      - '${KONGA_WEB_PORT}:1337'
    links:
      - kong-gateway
      - kong-database
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=${KONG_PG_USER}
      - DB_PASSWORD=${KONG_PG_PASSWORD}
      - TOKEN_SECRET=${KONGA_SECRET_KEY}
      - DB_DATABASE=${KONG_PG_DB}
      - NODE_ENV=${KONGA_MODE}
    depends_on:
      - kong-database

